# Generated by Django 3.0.5 on 2020-04-11 21:50

from django.db import migrations, models
import django.db.models.deletion
import scraper_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('img_urls_file', models.URLField(default=scraper_app.models.get_default_file_out_path)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='images')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper_app.Website')),
            ],
        ),
    ]
