# Generated by Django 3.0.5 on 2020-04-11 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='url',
            new_name='image_file',
        ),
    ]
